# Generated by Django 4.1.7 on 2023-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='dietary_fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='image',
            field=models.ImageField(blank=True, default='nutritions/default.png', upload_to='nutritions/'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='total_carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='total_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_D',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
